package compiladorcool.lexical;

public enum TokenType {
    TYPE_IDENTIFIER, OBJECT_IDENTIFIER, INTEGER, STRING,
    CLASS, ELSE, FALSE, FI, IF, IN, INHERITS, ISVOID, LET, 
    LOOP, POOL, THEN, WHILE, CASE, ESAC, NEW, OF, NOT, TRUE,
    ADD, SUB, MULT, DIV, COMPLEMENT, LT, LTE, EQUAL, ASSIGN,
    COLON, ARROW, OPEN_PARENTHESES, CLOSE_PARENTHESES,
    OPEN_BRACES, CLOSE_BRACES, AT, DOT, COMMA, SEMICOLON, EXPR
}
