package compiladorcool;

public enum NodeType {
    CLASS, ATTRIBUTE, METHOD, ASSIGNMENT, DISPATCH, IF, WHILE, 
    SEQUENCE, LET, CASE, NEW, ISVOID, ARITHMETIC, COMPLEMENT, METHOD_CALL,
    COMPARE, EQUAL, NOT, ID, INTEGER, STRING, BOOL, AMONG_PARENTHESES,
}