package compiladorcool;

public enum NodeType {
    CLASS, ATTRIBUTE, METHOD, ASSIGNMENT, DISPATCH, IF, WHILE, 
    SEQUENCE, LET, CASE, NEW, ISVOID, ARITHMETIC, COMPLEMENT, 
    COMPARE, EQUAL, NOT, ID, INTEGER, STRING, BOOL
}